DATASET: 'demo'
BATCH_SIZE: 1
SAVE_SCENE_MESH: True
SAVE_INCREMENTAL: False
VIS_INCREMENTAL: False
REDUCE_GPU_MEM: True  # Drastically reduces GPU memory and will slow down inference a bit.
LOGDIR: './checkpoints'
SAVE_FREQ: 1
MODE: 'test'

TEST:
  # Change your own data path here
  PATH: '/home/sunjiaming/Repositories/NeuralFusion/data/neucon_tianren_demo/tianren_zihao'
  N_VIEWS: 9
  N_WORKERS: 1

MODEL:
  N_LAYER: 3
  N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.04
  TRAIN_NUM_SAMPLE: [4096, 16384, 65536]
  TEST_NUM_SAMPLE: [4096, 16384, 65536]

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True
    HIDDEN_DIM: 64

    AVERAGE: False
    FULL: True

  LW: [1.0, 0.8, 0.64]

  THRESHOLDS: [0, 0, 0]
  POS_WEIGHT: 1.5

